# Generated by Django 4.2.3 on 2023-08-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0002_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='profile',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
