# Generated by Django 4.2.3 on 2023-08-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0003_task_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='customProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(blank=True, upload_to='image/')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='profile',
        ),
    ]
